### ISSUE TITLE
Font family and line height overwrite

### ISSUE THREAD

**Issue by claudio-moya** [philcockfield/storybook-host#43]
Hi,

Thanks for the cool decorator, we are using it now in our Design System.

I just notice that the host styles from the css classes are affecting some core settings such as `font-family` and `line-height`.

In my case is affecting my project fonts definition and this don't happen with other decorators I use.

You can try by removing the css modules support and use inline styles on you final build to prevent css issues.

I attached a screenshot as reference.

![font-family-issue](https://user-images.githubusercontent.com/10554673/50129598-12438480-02bd-11e9-8db7-8939f71842d8.png)

**Comment by swapkats** [comment]
+1

**Comment by KhodeN** [comment]
Temporary workaround:
```css
/* see https://github.com/philcockfield/storybook-host/issues/43 */
[data-css-18sl43g] {
   font-family: inherit !important;
   line-height: inherit !important;
}
```
